# -*- coding: utf-8 -*-
"""aluno7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ZFPbRv8uIFTOWuCBOCtErM9AOUEMLE6
"""

import time
var = 0
while var <= 5:
    print(var)
    time.sleep(2)
    var = var + 1

from time import sleep
itens = ['ana','luca','wollas','davi','samuel']
for item in itens:
    print(item)
    sleep(2)

sala = []
while len(sala) <= 5:
    nome = str(input('nomes de alunos: '))
    sala.append(nome)
    print(sala)

sala = []
while len(sala) <= 5:
    nome = str(input('nomes de alunos: '))
    sala.append(nome)
for aluno in sala:
    print(aluno)

grupo = []

while len(grupo)<=2:
    pessoa = input('adicionar uma pessoa ao grupo: ')
    grupo.append(pessoas)
    qtd = 0
    while qtd <= len(grupo):
        qtd = qtd + 1

nomes=[]
idades=[]
alturas=[]

cadastro=int(input('quantas pessoas tem na casa? '))
c=1
i=0
while c<= cadastro:
    nome = str(input('nome da pessoa'))
    idade = int(input(f'informe a idade {nome}: '))
    altura = float(input(f'informe a altura {nome}: '))
    nomes.append(nome)
    idades.append(idade)
    alturas.append(altura)
    c+=1
    while i <= cadastro-1:
        print(f'nome {nome[i]} , idade {idades[i]} , altura {alturas[i]} ')
        i+=1

lista = [True, 'ana', 'r$1.00', 'palma da banana']
c=0
while len(lista)>c:
    print(lista[c])
    c+=1

a=('cachorro',2,1,4,True, ['item1','item2'])
type(a)

